const presets = {
    'Wisp': {
        speed: 0.7,
        iterations: 11,
        scale: 0.112,
        dotFactor: 0.28,
        vOffset: 0.0,
        intensityFactor: 1.0,
        expFactor: 4.73,
        redFactor: 1.5,
        greenFactor: 1.1,
        blueFactor: 1.0,
        colorShift: 0.8,
        // Logo settings
        logoInteractStrength: 0.5,
    },
    'Logo Glow': {
        speed: 1.2,
        iterations: 10,
        scale: 0.15,
        dotFactor: 0.3,
        vOffset: 3.2,
        intensityFactor: 0.18,
        expFactor: 0.8,
        redFactor: 0.8,
        greenFactor: 0.6,
        blueFactor: 1.2,
        colorShift: 0.5,
        // Logo settings
        logoInteractStrength: 0.7,
    },
    'Logo Emboss': {
        speed: 0.9,
        iterations: 8,
        scale: 0.22,
        dotFactor: 0.5,
        vOffset: 1.8,
        intensityFactor: 0.2,
        expFactor: 3.0,
        redFactor: 0.2,
        greenFactor: 0.4,
        blueFactor: 0.8,
        colorShift: 0.3,
        // Logo settings
        logoInteractStrength: 0.9,
    },
    'Oil Slick': {
        speed: 0.67,
        iterations: 8,
        scale: 0.22,
        dotFactor: 0.15,
        dotMultiplier: 0.79,
        vOffset: 6.3,
        intensityFactor: 0.9,
        expFactor: 2.8,
        redFactor: -0.9,
        greenFactor: -1.9,
        blueFactor: -0.2,
        colorShift: 0.6,
        // Logo settings
        logoInteractStrength: 0.35,
    },
    'Solar Flare': {
        speed: 2.2,
        iterations: 7,
        scale: 0.11,
        dotFactor: 0.32,
        vOffset: 10.0,
        intensityFactor: 0.12,
        expFactor: 12.0,
        redFactor: 1.8,
        greenFactor: 0.4,
        blueFactor: -0.4,
        colorShift: 0.0,
        // Logo settings
        logoInteractStrength: 0.6,
    },
    'Deep Ocean': {
        speed: 0.6,
        iterations: 12,
        scale: 0.25,
        dotFactor: 0.8,
        vOffset: 0.6,
        intensityFactor: 0.15,
        expFactor: 4.5,
        redFactor: -1.2,
        greenFactor: -0.2,
        blueFactor: 1.5,
        colorShift: 0.3,
        // Logo settings
        logoInteractStrength: 0.5,
    },
    'The Matrix': {
        speed: 1.2,
        iterations: 8,
        scale: 0.18,
        dotFactor: 0.75,
        vOffset: 0.9,
        intensityFactor: 0.22,
        expFactor: 2.0,
        redFactor: -1.5,
        greenFactor: 1.8,
        blueFactor: -1.5,
        colorShift: 0.1,
        // Logo settings
        logoInteractStrength: 0.8,
    },
    'Rainbow': {
        speed: 0.5,
        iterations: 11,
        scale: 0.402,
        dotFactor: 1.17,
        vOffset: 6.0,
        intensityFactor: 0.18,
        expFactor: 2.59,
        redFactor: -1.3,
        greenFactor: 1.5,
        blueFactor: 0.6,
        colorShift: 0,
        // Logo settings
        logoInteractStrength: 0.64,
    }
};