const presets = {
    'Glow': {
        speed: 0.34,
        iterations: 15,
        scale: 3.11,
        dotFactor: 0.66,
        dotMultiplier: 0.36,
        vOffset: 6.0,
        intensityFactor: 0.34,
        expFactor: 8.9,
        redFactor: 0.2,
        greenFactor: 0.0,
        blueFactor: -0.2,
        colorShift: 0.5,
        // Logo settings
        logoInteractStrength: 0.66,
    },
    'Wisp': {
        speed: 0.7,
        iterations: 11,
        scale: 0.112,
        dotFactor: 0.28,
        vOffset: 0.0,
        intensityFactor: 1.0,
        expFactor: 4.73,
        redFactor: 1.5,
        greenFactor: 1.1,
        blueFactor: 1.0,
        colorShift: 0.8,
        // Logo settings
        logoInteractStrength: 0.5,
    },
    'Smoke': {
        speed: 1.42,
        iterations: 6,
        scale: 0.17,
        dotFactor: 0.27,
        dotMultiplier: 0.0,
        vOffset: 4.8,
        intensityFactor: 0.57,
        expFactor: 4.9,
        redFactor: -0.4,
        greenFactor: -0.3,
        blueFactor: 0.1,
        colorShift: 0.0,
        // Logo settings
        logoInteractStrength: 0.25,
    },
    'Oil Slick': {
        speed: 0.67,
        iterations: 8,
        scale: 0.22,
        dotFactor: 0.15,
        dotMultiplier: 0.79,
        vOffset: 6.3,
        intensityFactor: 0.9,
        expFactor: 2.8,
        redFactor: -0.9,
        greenFactor: -1.9,
        blueFactor: -0.2,
        colorShift: 2.0,
        // Logo settings
        logoInteractStrength: 0.35,
    },
    'Chrome': {
        speed: 0.4,
        iterations: 15,
        scale: 3.12,
        dotFactor: 0.04,
        dotMultiplier: 0.21,
        vOffset: 5.1,
        intensityFactor: 0.73,
        expFactor: 0.2,
        redFactor: 1.1,
        greenFactor: 0.7,
        blueFactor: 0.9,
        colorShift: 0.9,
        // Logo settings
        logoInteractStrength: 0.4,
    },
    'Rainbow': {
        speed: 0.56,
        iterations: 11,
        scale: 1.2,
        dotFactor: 0.699,
        dotMultiplier: 0.56,
        vOffset: 6.1,
        intensityFactor: 0.258,
        expFactor: 6.0,
        redFactor: -0.2,
        greenFactor: 1.1,
        blueFactor: -1.7,
        colorShift: 0,
        // Logo settings
        logoInteractStrength: 0.38,
    },
    'Liquid': {
        speed: 0.33,
        iterations: 14,
        scale: 1.49,
        dotFactor: 0.03,
        dotMultiplier: 0.66,
        vOffset: 0.1,
        intensityFactor: 0.07,
        expFactor: 4.5,
        redFactor: -1.2,
        greenFactor: 0.6,
        blueFactor: 0.6,
        colorShift: 0.2,
        // Logo settings
        logoInteractStrength: 0.39,
    },
};